# -*- encoding:utf-8 -*-
import json
import os.path, sys, logging

mydir = os.path.dirname(os.path.abspath(__file__))
app_dir = os.path.join(mydir, '..')
sys.path.insert(0, app_dir)

runconfig_file = os.path.join(mydir, 'runconfig.json') #this configuration is to set environment and dbs, services_config, reset etc. auto generated by genconf.py
instance_config_dir = os.path.join(app_dir, 'instance') #flask by default supports instance configuration dir.
instance_config_file = os.path.join(app_dir, 'instance', 'config.json') #this config file is for configuration of app instance, like secretkey, session_cookie_name, etc.

from vedavaapi.api import app
from vedavaapi.common import start_app

logging.basicConfig(
  level=logging.INFO,
  format="%(levelname)s: %(asctime)s {%(filename)s:%(lineno)d}: %(message)s "
)

runconfig = {}

def update_runconfig():
    with open(runconfig_file, 'rb') as rc:
        runconfig.update(json.loads(rc.read().decode('utf-8')))
        runconfig['services'] = [str(service) for service in runconfig['services']]

    logging.info('starting app with configuration :' + json.dumps({'services' : runconfig['services'], 'config_root_dir' : runconfig['config_root_dir'], 'reset' : runconfig['reset']}, indent=3))


def setup_app():
    if not os.path.exists(instance_config_dir):
        try:
            os.makedirs(instance_config_dir)
        except:
            raise

    if runconfig['reset']:
        try:
            icjson = json.loads(open(instance_config_file, 'rb').read().decode('utf-8'))
        except:
            icjson = {}
        with open(instance_config_file, 'wb') as icf:
            icjson_update = {"SESSION_COOKIE_NAME" : "vedavaapi_session"}
            from base64 import b64encode
            icjson_update['SECRET_KEY'] = b64encode(os.urandom(24)).decode('utf-8')

            icjson.update(icjson_update)
            icf.write(json.dumps(icjson, indent=4, ensure_ascii=True).encode("utf-8"))
            app.config.update(icjson)
            print(app.config)
    start_app(app, runconfig['config_root_dir'], runconfig['services'], runconfig['reset'])

def main(argv):
    update_runconfig()
    setup_app()
    if sys.version_info >= (3,3):
        #sanskrit_data imports urllib.request, which is not there in 2.x.
        from sanskrit_data import file_helper
        logging.info("Available on the following URLs:")
        for line in file_helper.run_command(["/sbin/ifconfig"]).split("\n"):
            import re
            m = re.match('\s*inet addr:(.*?) .*', line)
            if m:
                logging.info("    http://" + m.group(1) + ":" + str(runconfig['port']) + "/")
    app.run(
        host=runconfig['host'],
        port=runconfig['port'],
        debug=runconfig['debug'],
        use_reloader=False
    )


if __name__ == "__main__":
  logging.info("Running in stand-alone mode.")
  main(sys.argv[:])
else:
  logging.info("Likely running as a WSGI app.")
  update_runconfig()
  setup_app()
